// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uyanda.Customer.Persistence;

#nullable disable

namespace Uyanda.Customer.Persistence.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20230407200527_InitialiseDummyCustomerData")]
    partial class InitialiseDummyCustomerData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Customer")
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Uyanda.Customer.Persistence.Entities.ContactDetailsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts", "Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "dummyemail@example.com",
                            PhoneNumber = "0720000111"
                        });
                });

            modelBuilder.Entity("Uyanda.Customer.Persistence.Entities.CustomerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ContactDetailsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactDetailsId")
                        .IsUnique();

                    b.ToTable("Customers", "Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactDetailsId = 1,
                            Name = "The Rza",
                            Points = 5,
                            Surname = "The Gza"
                        });
                });

            modelBuilder.Entity("Uyanda.Customer.Persistence.Entities.CustomerEntity", b =>
                {
                    b.HasOne("Uyanda.Customer.Persistence.Entities.ContactDetailsEntity", "ContactDetails")
                        .WithMany()
                        .HasForeignKey("ContactDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
